// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 9/26/2026, 3:42:51 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["/Users/sila/Desktop/fast-news/web/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/sila/Desktop/fast-news/web/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/sila/Desktop/fast-news/web/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/sila/Desktop/fast-news/web/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/sila/Desktop/fast-news/web/plugins/**/*.{js,ts,mjs}","/Users/sila/Desktop/fast-news/web/composables/**/*.{js,ts,mjs}","/Users/sila/Desktop/fast-news/web/utils/**/*.{js,ts,mjs}","/Users/sila/Desktop/fast-news/web/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/sila/Desktop/fast-news/web/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/sila/Desktop/fast-news/web/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/sila/Desktop/fast-news/web/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;